// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowcaseCrm.Connections.ShowcaseCrm;

#nullable disable

namespace ShowcaseCrm.Connections.ShowcaseCrm.Migrations
{
    [DbContext(typeof(ShowcaseCrmContext))]
    [Migration("20260220084928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "IX_contacts_CompanyId");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LeadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "IX_deals_CompanyId");

                    b.HasIndex(new[] { "ContactId" }, "IX_deals_ContactId");

                    b.HasIndex(new[] { "LeadId" }, "IX_deals_LeadId");

                    b.HasIndex(new[] { "StageId" }, "IX_deals_StageId");

                    b.ToTable("deals");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.DealStage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("deal_stages");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContactId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "IX_leads_CompanyId");

                    b.HasIndex(new[] { "ContactId" }, "IX_leads_ContactId");

                    b.HasIndex(new[] { "StatusId" }, "IX_leads_StatusId");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("lead_statuses");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Contact", b =>
                {
                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Deal", b =>
                {
                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Company", "Company")
                        .WithMany("Deals")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Contact", "Contact")
                        .WithMany("Deals")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Lead", "Lead")
                        .WithMany("Deals")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.DealStage", "Stage")
                        .WithMany("Deals")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Lead");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Lead", b =>
                {
                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Company", "Company")
                        .WithMany("Leads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.Contact", "Contact")
                        .WithMany("Leads")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShowcaseCrm.Connections.ShowcaseCrm.LeadStatus", "Status")
                        .WithMany("Leads")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Contact");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Deals");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Contact", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.DealStage", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.Lead", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("ShowcaseCrm.Connections.ShowcaseCrm.LeadStatus", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
